"""

Revision ID: 3d91fe545787
Revises: 
Create Date: 2020-06-04 16:56:37.525454

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3d91fe545787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sms_message',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_name', sa.Enum('IQSMS', 'STREAM_TELECOM', 'SMSC', name='smsprovider'), nullable=True),
        sa.Column('provider_message_id', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_sms_message_id'), 'sms_message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_message_id'), table_name='sms_message')
    op.drop_table('sms_message')
    # ### end Alembic commands ###
