# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='sms.proto',
    package='sms',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\tsms.proto\x12\x03sms\")\n\nSmsRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1b\n\x0bSmsResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t22\n\x03Sms\x12+\n\x04Send\x12\x0f.sms.SmsRequest\x1a\x10.sms.SmsResponse\"\x00\x62\x06proto3',
)


_SMSREQUEST = _descriptor.Descriptor(
    name='SmsRequest',
    full_name='sms.SmsRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='phone',
            full_name='sms.SmsRequest.phone',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name='text',
            full_name='sms.SmsRequest.text',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=18,
    serialized_end=59,
)


_SMSRESPONSE = _descriptor.Descriptor(
    name='SmsResponse',
    full_name='sms.SmsResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='code',
            full_name='sms.SmsResponse.code',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=61,
    serialized_end=88,
)

DESCRIPTOR.message_types_by_name['SmsRequest'] = _SMSREQUEST
DESCRIPTOR.message_types_by_name['SmsResponse'] = _SMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmsRequest = _reflection.GeneratedProtocolMessageType(
    'SmsRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _SMSREQUEST,
        '__module__': 'sms_pb2'
        # @@protoc_insertion_point(class_scope:sms.SmsRequest)
    },
)
_sym_db.RegisterMessage(SmsRequest)

SmsResponse = _reflection.GeneratedProtocolMessageType(
    'SmsResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _SMSRESPONSE,
        '__module__': 'sms_pb2'
        # @@protoc_insertion_point(class_scope:sms.SmsResponse)
    },
)
_sym_db.RegisterMessage(SmsResponse)


_SMS = _descriptor.ServiceDescriptor(
    name='Sms',
    full_name='sms.Sms',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=90,
    serialized_end=140,
    methods=[
        _descriptor.MethodDescriptor(
            name='Send',
            full_name='sms.Sms.Send',
            index=0,
            containing_service=None,
            input_type=_SMSREQUEST,
            output_type=_SMSRESPONSE,
            serialized_options=None,
        )
    ],
)
_sym_db.RegisterServiceDescriptor(_SMS)

DESCRIPTOR.services_by_name['Sms'] = _SMS

# @@protoc_insertion_point(module_scope)
